<a href="https://colab.research.google.com/github/eshikajindal24/UCS547_Accelerated_data_science/blob/main/UCS547_102303954_Assign_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ASSIGNMENT 1**

1. Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) )

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
rev = arr[::-1]
rev

array([5, 4, 6, 3, 2, 1])

2. Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [6]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comp = np.array_equal(arr1,arr2)
comp

True

3. Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, 3])

In [17]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
frequency = np.bincount(x)
most_freq = np.argmax(frequency)
i = np.where(x==most_freq)
print("Freq - ",most_freq)
print("Indices - ",i)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, 3])
freq = np.bincount(y)
most_freq_y = np.argmax(freq)
j = np.where(y==most_freq_y)
print("Freq - ",most_freq_y)
print("Indices - ",j)

Freq -  1
Indices -  (array([0, 5, 7, 8, 9]),)
Freq -  3
Indices -  (array([ 4,  8,  9, 10]),)


4. For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
find i. Sum of all elements
ii. Sum of all element’s row-wise
iii. Sum of all element’s column-wise.

In [7]:
import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
# (i)
total = np.sum(gfg)
print(total)

# (ii)
total_row = np.sum(gfg, axis=1)
print(total_row)

# (iii)
total_col = np.sum(gfg, axis=0)
print(total_col)

45
[[14]
 [16]
 [15]]
[[20  9 16]]
